about/urls.py
from django.urls import path
from .views import about

urlpatterns = [
    path('',about,name='about'),
]

blog/urls.py
from django.urls import path
from .views import all_blogs,detail
app_name = 'blog'
urlpatterns = [
    path('',all_blogs,name='all_blogs'),
    path('<int:blog_id>',detail,name='detail')
]

home/urls.py
from django.urls import path,include
from .views import home
urlpatterns = [
    path('', home,name='home'),
]

myportfolio/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('',home,name='portfolio'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from home.views import home
from about.views import about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('blog/',include('blog.urls')),
    path('about/',include('about.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    img = models.ImageField(blank=True)
    title = models.CharField(max_length=100,blank=True)
    description = models.TextField(blank=True)
    title2 = models.CharField(max_length=100,blank=True)
    description2 = models.TextField(blank=True)
    title3 = models.CharField(max_length=100,blank=True)
    description3 = models.TextField(blank=True)
    title4 = models.CharField(max_length=100,blank=True)
    title5 = models.CharField(max_length=100,blank=True)
    email = models.CharField(max_length=100,blank=True)
    img2 = models.ImageField(blank=True)
    img3 = models.ImageField(blank=True)
    onimg3 = models.CharField(max_length=100,blank=True)
    onimgbtn = models.CharField(max_length=100,blank=True)
    description4 = models.TextField(blank=True)
    logo = models.ImageField(blank=True)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

myportfolio/models.py
from django.db import models

# Create your models here.
class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

services/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from .models import About
# Create your views here.
def about(request):
    about = About.objects.all()

    return render(request,'about/about.html',{'about':about})
    

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home/index.html',{'home':home})

myportfolio/views.py
from django.shortcuts import render
from .models import Portfolio
# Create your views here.
def home(request):
    projects = Portfolio.objects.all()

    return render(request,'myportfolio/index.html',{'projects':projects})

services/views.py
from django.shortcuts import render

# Create your views here.

about/templates/about/about.html
{% extends 'about/base.html' %}
{% block title %} <title>About</title> {% endblock %}
{% block content %}

{% for everything in about %}
<img src="{{everything.img.url}}" class="img-fluid position" alt="Responsive image">
<div class="container">
    <div class="paddingTopBottom">
        <h1 id="size">About Me</h1>
        <span class="color">
            <a href=".." class="color">Home</a>
            /
            <a href="#" class="color">About</a>
        </span>
    </div>
    
    <div class="flex paddingTop center justify-content">
        <div><img src="{{everything.img2.url}}" alt=""></div>
        <div>
            <h1>{{everything.title}}</h1>
            <p>{{everything.description}}</p>
            <h1>{{everything.title2}}</h1>
            <p>{{everything.description2}}</p>
        </div>
    </div>
    <div>
        <div>
            <h2>{{everything.title3}}</h2>
            <p>{{everything.description3}}</p>
        </div>
        <div>
            <h1>{{everything.title4}}</h1>
            <p>{{everything.title5}}</p>
            <a href="#">{{everything.email}}</a>
        </div>
    </div>
    <div>
        <img src="{{everything.img3.url}}" class="img-fluid" alt="Responsive image">
        <h1>{{everything.onimg3}}</h1>
        <button type="submit">{{everything.onimgbtn}}</button>
    </div>
    
</div>

{% endfor%}
{% endblock %}

about/templates/about/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
        href="https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@500&family=Roboto+Mono:wght@500&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Arapey&family=Roboto+Mono:wght@500&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="bootstrap.min.css">    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="index.css">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">

    {% block title %} {% endblock %}
    
</head>

<body>
    <nav>
        <div class="navchild">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link active log" href=".."><img src="{% static 'images/log.png' %}" alt=""></a>
                </li>
            </ul>
            <div class="divv">
                <ul class="nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active manu" href="..">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Contact</a>
                    </li>
                    <li class="nav-item">
                        <span><a class="nav-link navbutton" href="#">Get Free Consultent</a></span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <footer class="back">
        <div class="container">
            <div class="footerCenter"> 
                <div>
                    <div><img src="{% static 'images/log.png' %}" alt=""></div>
                    <a href="#">aslamjon.ibragimov@gmail.com</a>
                </div>
            </div>
            <div class="flex">
                <div>
                    <p>Copyright ©2020 All rights reserved | This template is made with 
                        <i class="fas fa-heart"></i>
                        <img src="{% static 'images/heart-solid.svg' %}" alt="" class="heart">
                    </p>
                </div>
                <div><p>Stay Connected</p></div>
            </div>
        </div>
    </footer>
</body>

</html>

blog/templates/blog/all_blogs.html
<h2>all Blogs {{blogs.count}}</h2>
{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
<h5>{{blog.date |date:'d M Y' |upper}}</h5>
<p>{{blog.description| safe | truncatechars:100}}</p>
{% endfor %}

blog/templates/blog/detail.html
<h1>{{blog.title}}</h1>
<h3>{{blog.date |date:'d M Y' |upper}}</h3>
<p>{{blog.description| safe}}</p>

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
        href="https://fonts.googleapis.com/css2?family=Frank+Ruhl+Libre:wght@500&family=Roboto+Mono:wght@500&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Arapey&family=Roboto+Mono:wght@500&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">


    {% block title %} {% endblock %}
</head>

<body>
    <nav>
        <div class="navchild">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link active log" href="#"><img src="images/log.png" alt=""></a>
                </li>
            </ul>
            <div class="divv">
                <ul class="nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active manu" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="about/">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link manu" href="#">Contact</a>
                    </li>
                    <li class="nav-item">
                        <span><a class="nav-link navbutton" href="#">Get Free Consultent</a></span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %}


{% block title %} <title>Personal HTML-5 Template</title> {% endblock %}



{% block content %}
<div class="forimg">
  <div class="forthem">
    <span class="them">Get Every Single Solutions.</span>
    <h1 class="h1">I’m Designer Haris F. Watson</h1>
    <p class="introdaction">jhorem rfpsum golor sidt amet, consectetur adipiscing elit, eiusmod tempor incididunt utcjhg
      labore bet dolore magna aliqua. Quis ipsum suspendisse ultrices gravida.</p>
    <div class="dws">
      <a href="#" class="butt">Learn More</a>
      <a href="#" class="butt2">Hire me</a>
    </div>
  </div>
</div>
<div class="include">
  <div class="secound">
    <h2 class="mavzu">Designing With Passion While Exploring The World.</h2>
    <p class="info">Consectetur adipiscing elit, sed do eiusmod tempor ididunt ut labore et dolore magna aliqua. Quis
      ipsum suspendisces gravida. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus.</p>
    <p class="info2">Consectetur adipiscing elit, sed do eiusmod tempor ididunt ut labore et dolore magna aliqua. </p>
  </div>
  <div class="secound">
    <h1 class="abo">Any Type Of Query
      & Discussion.</h1>
    <p class="ppp">Late talk with me</p>
    <div class="address"><a href="#" class="email">hire@colorlib.com</a><i class="strel"></i></div>
  </div>
</div>
<div class="abservice">
  <p id="service">What Services you will Get from me!</p>
</div>
<div class="group">
  <div class="one">
    <div class="helper">
      <div class="flaticon-pen"><img src="images/icons8-design-96.png" alt="" height="60px"></div>
    </div>
    <div class="helpfortext"><a href="#" class="firstthem">UI/UX Design</a>
      <p class="infor1">Free resource that will help nderstand thecv designc process and improve theroi nderstand the
        design process andisei impro are of vquality.</p>
    </div>
  </div>
  <div class="one">
    <div class="helper2">
      <div class="ads"><img src="images/megaphone.png" alt="" height="60px"></div>
    </div>
    <div class="helpfortext"><a href="#" class="firstthem">Digital Marketing</a>
      <p class="infor1">Free resource that will help nderstand thecv designc process and improve theroi nderstand the
        design process andisei impro are of vquality.</p>
    </div>
  </div>
  <div class="one">
    <div class="helper3">
      <div class="web"><img src="images/landing-page.png" alt="" height="50px"></div>
    </div>
    <div class="helpfortext"><a href="#" class="firstthem">Web Design</a>
      <p class="infor1">Free resource that will help nderstand thecv designc process and improve theroi nderstand the
        design process andisei impro are of vquality.</p>
    </div>
  </div>
</div>
<div class="group2">
  <div class="themphoto">
    <p class="text15">What Services you will Get from me!</p>
  </div>
</div>
{% endblock %}

myportfolio/templates/myportfolio/home.html
<h1>Bu meni qilgan ishlarim</h1>

{% for project in projects %}
<h2>{{project.title}}</h2>
<p>{{project.description}}</p>
<img src="{{project.image.url}}" alt="" height="300px">
<br>
{% if project.url %}
<a href="{{project.url}}">Link</a>
{% endif %}

{% endfor %}